# Generated by Django 3.2 on 2022-06-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_shiping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_address',
            new_name='shipping_address',
        ),
    ]
