# Generated by Django 3.2 on 2022-06-14 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_complate_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
