# Generated by Django 3.2 on 2022-06-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220614_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_complate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
