# Generated by Django 3.2.15 on 2022-09-20 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlashSaleOn_date', models.DateField(default=django.utils.timezone.now)),
                ('FlashSale_expire_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'FlashSale',
                'verbose_name_plural': 'FlashSales',
            },
        ),
    ]
