# Generated by Django 3.2.15 on 2022-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_flashsale_flashsaleon_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='FlashSale_expire_date',
            field=models.IntegerField(),
        ),
    ]
