# Generated by Django 3.2.15 on 2022-10-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_campaign_campaignproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignproduct',
            old_name='campaing_category',
            new_name='campaign_category',
        ),
    ]
