# Generated by Django 3.2.15 on 2022-10-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_campaing_category_campaignproduct_campaign_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaign Category'},
        ),
        migrations.AlterModelOptions(
            name='campaignproduct',
            options={'verbose_name': 'CampaignProduct', 'verbose_name_plural': 'CampaignProduct'},
        ),
    ]
