# Generated by Django 3.2.15 on 2022-10-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20221013_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shiping_charge',
        ),
        migrations.AddField(
            model_name='order',
            name='shiping_charge_inside_cha',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shiping_charge_outside_dhaka',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='order',
            name='total_due_amount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_paid_amount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
