# Generated by Django 3.2.15 on 2022-10-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20221015_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shiping_charge_inside_cha',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shiping_charge_outside_dhaka',
        ),
    ]
