# Generated by Django 3.2.15 on 2022-10-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20221015_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheDayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'CampaignProduct',
                'verbose_name_plural': 'CampaignProduct',
            },
        ),
    ]
