# Generated by Django 3.2.15 on 2022-10-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_dealofthedayproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealofthedayproduct',
            options={'verbose_name': 'Deal Of The Day', 'verbose_name_plural': 'Deal Of The Day'},
        ),
    ]
