# Generated by Django 3.2.15 on 2022-10-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], default=5),
        ),
    ]
