# Generated by Django 3.2.15 on 2022-10-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_order_total_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_due_amount',
            new_name='due_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
