# Generated by Django 3.2.15 on 2022-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20221023_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_amount',
            field=models.CharField(blank=True, default=0, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.CharField(blank=True, default=0, max_length=150, null=True),
        ),
    ]
