# Generated by Django 3.2.15 on 2022-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20221023_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Logo Image')),
            ],
        ),
    ]
