# Generated by Django 3.2.15 on 2022-10-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_websitelogo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_type',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sub_title',
        ),
    ]
