# Generated by Django 3.2.15 on 2022-10-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20221026_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductdata',
            options={'ordering': ['-id'], 'verbose_name': 'ConductData', 'verbose_name_plural': 'ConductData'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'ordering': ['-id']},
        ),
    ]
