# Generated by Django 3.2.15 on 2022-10-27 08:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20221026_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort_discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
