# Generated by Django 3.2.15 on 2022-11-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_area', models.CharField(max_length=150)),
                ('delivery_area_id', models.CharField(max_length=150)),
                ('parcel_weight', models.CharField(max_length=150)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
