# Generated by Django 3.2.15 on 2022-11-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_percel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Percel',
        ),
    ]
