# Generated by Django 3.2.15 on 2022-11-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_delete_percel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPercel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=150, null=True)),
                ('merchant_invoice_id', models.CharField(blank=True, max_length=150, null=True)),
                ('cash_collection_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('delivery_area', models.CharField(max_length=150)),
                ('delivery_area_id', models.CharField(max_length=150)),
                ('parcel_weight', models.CharField(max_length=150)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
