# Generated by Django 3.2.15 on 2022-11-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20221117_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_purchase_price',
            field=models.IntegerField(),
        ),
    ]
