# Generated by Django 3.2.15 on 2022-11-17 07:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
