# Generated by Django 3.2.15 on 2022-11-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_alter_product_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sort_discription',
        ),
    ]
