# Generated by Django 3.2.15 on 2022-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_product_sort_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
