# Generated by Django 3.2.15 on 2022-11-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_flashsale_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='tile',
            field=models.CharField(max_length=150),
        ),
    ]
