# Generated by Django 3.2.15 on 2022-11-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_alter_flashsale_tile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsale',
            old_name='tile',
            new_name='title',
        ),
    ]
