# Generated by Django 3.2.15 on 2022-11-21 05:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_rename_tile_flashsale_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_information', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='MissionAndsVision',
            new_name='Mission',
        ),
    ]
