# Generated by Django 3.2.15 on 2022-11-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_auto_20221121_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpercel',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productpercel',
            name='cash_collection_amount',
            field=models.CharField(max_length=150),
        ),
    ]
