# Generated by Django 3.2.15 on 2022-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_remove_productpercel_cash_collection_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpercel',
            name='cash_collection_amount',
            field=models.CharField(default='500', max_length=150),
        ),
        migrations.AddField(
            model_name='productpercel',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
