# Generated by Django 3.2.15 on 2022-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_auto_20221123_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpercel',
            name='cash_collection_amount',
            field=models.CharField(blank=True, default='500', max_length=150, null=True),
        ),
    ]
