# Generated by Django 3.2.15 on 2022-11-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_alter_productpercel_cash_collection_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpercel',
            name='tracking_id',
        ),
    ]
