# Generated by Django 3.2.15 on 2022-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_auto_20221123_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_read_status',
            field=models.BooleanField(default=False),
        ),
    ]
