# Generated by Django 3.2.15 on 2022-11-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_order_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='abc', to='store.OrderItem'),
        ),
        migrations.DeleteModel(
            name='Order_Analysis',
        ),
    ]
