# Generated by Django 3.2.15 on 2022-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_traking_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
