# Generated by Django 3.2.15 on 2022-12-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_order_order_traking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_traking_number',
            new_name='redx_percel_traking_number',
        ),
        migrations.AddField(
            model_name='order',
            name='others_transport_trakink_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
