# Generated by Django 3.2.15 on 2022-12-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_auto_20221218_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='brand',
        ),
        migrations.AddField(
            model_name='banner',
            name='http_url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
