# Generated by Django 3.2 on 2022-06-10 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('upazila_or_thana', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('Village', models.CharField(max_length=150)),
                ('holding_number', models.CharField(max_length=150)),
                ('post_code', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('order_note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
