# Generated by Django 3.2.15 on 2022-10-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0002_shipingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipingaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shipingaddress',
            name='holding_number',
        ),
        migrations.RemoveField(
            model_name='shipingaddress',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='shipingaddress',
            name='post_office',
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='address_location',
            field=models.CharField(blank=True, choices=[('Inside Chittagong', 'Inside Chittagong'), ('Inside Chittagong', 'Insdte Chittagong')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
