# Generated by Django 3.2.15 on 2022-10-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0004_auto_20221015_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipingaddress',
            name='inside_chittagong',
        ),
        migrations.RemoveField(
            model_name='shipingaddress',
            name='outside_chittagong',
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='address_location',
            field=models.CharField(blank=True, choices=[('Inside Chittagong', 'Inside Chittagong'), ('Inside Chittagong', 'Insdte Chittagong')], max_length=100, null=True),
        ),
    ]
