# Generated by Django 3.2.15 on 2022-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0005_auto_20221015_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipingaddress',
            name='address_location',
            field=models.CharField(blank=True, choices=[('Inside Chittagong', 'Inside Chittagong'), ('Outside Chittagong', 'Outsdte Chittagong')], max_length=100, null=True),
        ),
    ]
