# Generated by Django 3.2.15 on 2022-10-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0006_alter_shipingaddress_address_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipingaddress',
            name='address_location',
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='inside_chittagong',
            field=models.BooleanField(default=False),
        ),
    ]
