# Generated by Django 3.2.15 on 2022-10-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0007_auto_20221015_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipingaddress',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
