# Generated by Django 3.2.15 on 2022-10-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0008_alter_shipingaddress_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipingaddress',
            name='Village',
        ),
        migrations.RemoveField(
            model_name='shipingaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='shipingaddress',
            name='inside_chittagong',
        ),
        migrations.RemoveField(
            model_name='shipingaddress',
            name='upazila_or_thana',
        ),
        migrations.AddField(
            model_name='shipingaddress',
            name='shiping_area',
            field=models.CharField(choices=[('Inside Chittagong', 'Inside Chittagong'), ('Inside Dhaka', 'Inside Dhaka'), ('Outside Dhaka', 'Outside Dhaka')], default='Inside Dhaka', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipingaddress',
            name='full_address',
            field=models.TextField(),
        ),
    ]
