# Generated by Django 3.2.15 on 2022-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0009_auto_20221017_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipingaddress',
            name='shiping_area',
            field=models.CharField(choices=[('Inside Chittagong', 'Inside Chittagong'), ('Inside Dhaka', 'Inside Dhaka'), ('Outside Dhaka', 'Outside Dhaka')], max_length=100),
        ),
    ]
