# Generated by Django 3.2.15 on 2022-12-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0014_bkashpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashpayment',
            name='createTime',
            field=models.CharField(max_length=150),
        ),
    ]
