# Generated by Django 3.2.15 on 2022-12-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0016_bkashpayment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPaymentExecute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(max_length=150)),
                ('createTime', models.CharField(max_length=150)),
                ('updateTime', models.CharField(max_length=150)),
                ('trxID', models.CharField(max_length=150)),
                ('transactionStatus', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=150)),
                ('intent', models.CharField(max_length=150)),
                ('merchantInvoiceNumber', models.CharField(max_length=150)),
                ('customerMsisdn', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'BkashExecute',
            },
        ),
    ]
