# Generated by Django 3.2.15 on 2022-12-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentApp', '0017_bkashpaymentexecute'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkashpaymentexecute',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
