# Generated by Django 3.2.15 on 2022-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0018_bkashpaymentexecute_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalTrxID', models.CharField(max_length=150)),
                ('refundTrxI', models.CharField(max_length=150)),
                ('transactionStatus', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=150)),
                ('charge', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'BkashPaymentRefund',
            },
        ),
        migrations.AlterModelOptions(
            name='bkashpaymentexecute',
            options={'verbose_name_plural': 'BkashPaymentExecute'},
        ),
    ]
