# Generated by Django 3.2.15 on 2022-12-12 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentApp', '0020_bkashpaymentrefund_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashpaymentexecute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
        migrations.AlterField(
            model_name='bkashpaymentrefund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
        ),
    ]
