# Generated by Django 3.2.15 on 2022-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0022_bkashpaymentrefund_completedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashpaymentrefund',
            name='completedTime',
            field=models.CharField(max_length=150),
        ),
    ]
