# Generated by Django 3.2.15 on 2022-12-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0023_alter_bkashpaymentrefund_completedtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bkashpaymentrefund',
            old_name='refundTrxI',
            new_name='refundTrxID',
        ),
    ]
