# Generated by Django 3.2.15 on 2022-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentApp', '0024_rename_refundtrxi_bkashpaymentrefund_refundtrxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipingaddress',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
