# Generated by Django 3.2.15 on 2023-06-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_dashboard', '0003_auto_20230614_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_product',
            old_name='product_name',
            new_name='sale_product_name',
        ),
    ]
