# Generated by Django 3.2.15 on 2023-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_dashboard', '0004_rename_product_name_sales_product_sale_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'return_purchase',
                'verbose_name_plural': 'return_purchases',
            },
        ),
    ]
